### ISSUE TITLE
Error Liquibase hanadb

### ISSUE THREAD

**Issue by cgrall4cloud** [lbitonti/liquibase-hana#11]
Hello,

i get the following error.
Can you please help me?

[ljs_output_9ed34e1_2017-07-18.txt](https://github.com/lbitonti/liquibase-hana/files/1155512/ljs_output_9ed34e1_2017-07-18.txt)

Thanks and Kind Regards,
Christoph

**Comment by lbitonti** [comment]
That's a jpa field definition error. Not much I can do I am afraid.
