### ISSUE TITLE
Question What is the relationship of this vs the "official" extension?

### ISSUE THREAD

**Issue by calle2010** [lbitonti/liquibase-hana#4]
I wonder what the relationship of this repository is with the "official" Liquibase extension (https://github.com/liquibase/liquibase-hanadb). As far as I understand Liquibase took an earlier version of this code and has refactored it meanwhile for newer releases of Liquibase. So the pull request https://github.com/lbitonti/liquibase-hana/pull/3 would not apply cleanly there.

Is there a plan to contribute the much needed improvements from here to the Liquibase repository again?

Kind regards,
Christian.

**Comment by lbitonti** [comment]
Hi Christian,
The "relationship" is that I implemented the first version of the extension and then I believe this was copied (not forked) in the main Liquibase repository by the Liquibase author(s). I am afraid there cannot be pull requests this way and updates will have to be merged manually. 
Best regards,Luigi

 


     On Wednesday, April 15, 2015 12:09 PM, Christian <notifications@github.com> wrote:
   

 I wonder what the relationship of this repository is with the "official" Liquibase extension (https://github.com/liquibase/liquibase-hanadb). As far as I understand Liquibase took an earlier version of this code and has refactored it meanwhile for newer releases of Liquibase. So the pull request #3 would not apply cleanly there.Is there a plan to contribute the much needed improvements from here to the Liquibase repository again?Kind regards,
Christian.—

**Comment by calle2010** [comment]
Thank you, Luigi. Understood.
Cheers,
Christian.
