### ISSUE TITLE
Support for VARBINARY data type

### ISSUE THREAD

**Issue by aamotharald** [lbitonti/liquibase-hana#9]
Hi Luigi, Hi Matthew,

can I get write access to the repository so that I can add the VARBINARY data type support? I have wwritten a liquibase.datatype.ext.VarbinaryTypeHanaDB and changed liquibase.datatype.ext.BlobTypeHanaDB to ignore VARBINARYs

**Comment by lbitonti** [comment]
Hi Harald,

Can you please create a pull request if you have changes you want to get included?

Thanks,
Luigi

**Comment by aamotharald** [comment]
Hi Luigi,

I am not sure if I have understood this procedure.
I have created a local branch and would like to push it so I can create a pull request with this branch.

But I am not allowed to push to the repo. Can you give me the rights to push to the repo? Otherwise I cannot create a pull request.

Best regards,

Harald

**Comment by aamotharald** [comment]
I now have now forked and created a pull request. Hope this works..

**Comment by aamotharald** [comment]
Hi Luigi,

thanks for merging. Closing the issue.

**Comment by lbitonti** [comment]
Thank you Harald. I've just made a 3.1.1 release which includes your PR.

Cheers,
Luigi
